name: 'Secret Scanning'

on:
  pull_request:
    branches:
      - main
      - master
      - develop

permissions: {}

concurrency:
  group: secret-scanning-${{ github.ref }}
  cancel-in-progress: true

jobs:
  secret-scan:
    name: 'Scan for secrets'
    uses: guiddeco/shared-workflows/.github/workflows/ci-secret-scanning.yaml@v1
    permissions:
      contents: read
      pull-requests: write
    with:
      fail_on_findings: false
